### ISSUE TITLE
Import external libs in web-workers

### ISSUE THREAD

**Issue by astrada-c** [patidar-suresh/angular6-webworker#1]
Is there specific configuration required to important external libs into the web workers?

For example
`import {interval} from 'rxjs';`

Will throw this error :
Uncaught ReferenceError: require is not defined external "rxjs":1

This happens with all external lib imports.

thx

**Comment by KGncT** [comment]
i take 
"GET http://localhost:4200/assets/workers/main.js 404 (Not Found)" message in console; also the webworker button doesnt work. May i take a solution please?

**Comment by patidar-suresh** [comment]
Can you let me know how are you trying to run this code? You may get this error if you run the code using command `ng serve`. The file `main.js` is created as part of webworker compilation process, so if that is skipped then the file won't be created and you will get 404 (not found) error. 
If you carefully look at `package.json` you will find couple of additional scripts defined to build the webworker code.
In order the run this code you need to run command `npm start` which internally build webworker and then serve the application using ng serve.
Let me know if this doesn't solve your problem.

**Comment by patidar-suresh** [comment]
Just FYI:- In this code we did some hack to run code due to a road block that we hit. Later I found a solution and created another example. You can find more details on [article](https://medium.com/@suresh.patidar/running-web-worker-in-angular-6-application-a-step-by-step-guide-74e88c566ba4) written on medium.
Example code for the same is available on [GitHub](https://github.com/patidar-suresh/webworker-in-angular6)

**Comment by patidar-suresh** [comment]
> Is there specific configuration required to important external libs into the web workers?
> 
> For example
> `import {interval} from 'rxjs';`
> 
> Will throw this error :
> Uncaught ReferenceError: require is not defined external "rxjs":1
> 
> This happens with all external lib imports.
> 
> thx

@vannaio Thank you for pointing this out. As you know that this example is created to complement the slide share presentation where we actually hit road block and made this working through some hacks. That hack doesn't work with including third party libraries but later I found another solution for the problem. 
I have described that elegant solution (without any hacks) in my [article](https://medium.com/@suresh.patidar/running-web-worker-in-angular-6-application-a-step-by-step-guide-74e88c566ba4) on Medium. A sample code for same is also added on [GitHub](https://github.com/patidar-suresh/webworker-in-angular6)
This is exactly same application as the one in current repository. I would request you to follow above article and code sample going forward.
I have already tested adding rxjs to it locally and it worked fine for me :)
here a change that I did in file `mocked-cpu-intensive.worker.ts` which printed the console logs for me.
```
import { WorkerMessage } from './shared/worker-message.model';
import { interval } from 'rxjs';

export class MockedCpuIntensiveWorker {

  public static doWork(value: WorkerMessage): WorkerMessage {
    const source = interval(1000);
    const subscribe = source.subscribe(val => console.log(val));
    const before = new Date();
    let count = 0;
    while (true) {
      count++;
      const now = new Date();
      if (now.valueOf() - before.valueOf() > value.data.duration) {
        break;
      }
    }
    return new WorkerMessage(value.topic, { iteration: count });
  }
}
```

**Comment by KGncT** [comment]
> Can you let me know how are you trying to run this code? You may get this error if you run the code using command `ng serve`. The file `main.js` is created as part of webworker compilation process, so if that is skipped then the file won't be created and you will get 404 (not found) error.
> If you carefully look at `package.json` you will find couple of additional scripts defined to build the webworker code.
> In order the run this code you need to run command `npm start` which internally build webworker and then serve the application using ng serve.
> Let me know if this doesn't solve your problem.

Thanks for paying attention. I didn't care the `npm run dev:worker` command stated in `package.json` file as `scripts->start`. When i run it first and then `ng serve`, it worked.
